### ISSUE TITLE
HTML parser for static pages

### ISSUE THREAD

**Issue by developerdino** [phpaustralia/jobs#5]
Moving conversation from #1 [Add _About_ section, to introduce the project purpose and scope]  to here so that we can merge PR.

@jclyons52 commented 3 days ago
We could do an md to html parser, so static pages can be viewed on github and the site. What did you have in mind for the content? A job site aimed at developer, where they can get feedback about job opportunities from other developers?

@bendechrai commented 3 days ago
@jclyons52 html parser is a good idea to make sure we don't diverge content between mediums :)

In mind for the content? As in the text copy, or the purpose of the site? I'm assuming latter.

Your description sounds like the vision I have. It's definitely aimed at developers and supporting the community. Recruiters will benefit from having an advertising channel that, hopefully, will become a trusted avenue by developers.

Most other online job ad sites seem clinical and recruiter focused. Potential applicants get job specs that aren't even relevant :/

**Comment by jclyons52** [comment]
I've added a controller an named the route. I went with docs rather than blog.
